steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '11.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'npm install'

  - script: make docker-test-up
    displayName: 'make docker-test-up'

  - script: npx wait-on -w 2000 tcp:45432 && npx wait-on -w 2000 tcp:41883
    displayName: 'Wait for dependencies to start up'
