version: '3'

services:
  api-server:
    image: jihartik/signalk-stash-api-server
    ports:
      - 3000:3000
    restart: always
    environment:
      ENVIRONMENT: production
  mqtt-input:
    image: jihartik/signalk-stash-mqtt-input
    restart: always
    environment:
      ENVIRONMENT: production
      MQTT_BROKER: mqtt://mqtt

  postgis:
    image: mdillon/postgis:10-alpine
    volumes:
     - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: signalk
      POSTGRES_PASSWORD: signalk
      POSTGRES_DB: signalk
  mqtt:
    image: eclipse-mosquitto
    ports:
     - 1883:1883
    volumes:
      - mosquitto:/mosquitto/data
    restart: always

volumes:
  pgdata:
  mosquitto:
