version: '3'

services:
  clickhouse-dev:
    image: yandex/clickhouse-server
    ports:
     - 58123:8123
     - 59000:9000
  postgis:
    image: mdillon/postgis:11-alpine
    ports:
     - 55432:5432
    volumes:
     - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: signalk
      POSTGRES_PASSWORD: signalk
      POSTGRES_DB: signalk
  mqtt:
    image: signalkstash/mosquitto
    build:
      context: .
      dockerfile: Dockerfile.mosquitto
    ports:
     - 51883:1883
    volumes:
      - mosquitto-data:/var/lib/mosquitto
    restart: always
  grafana:
    image: "grafana/grafana"
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources/dev:/etc/grafana/provisioning/datasources
    environment:
      GF_SECURITY_ADMIN_PASSWORD: klangis
      GF_INSTALL_PLUGINS: vertamedia-clickhouse-datasource


volumes:
  pgdata:
  mosquitto-data:
