FROM jllopis/mosquitto

COPY mosquitto.conf /etc/mosquitto/mosquitto.conf
COPY mosquitto-auth.conf /etc/mosquitto.d/mosquitto-auth.conf

RUN mkdir -p /var/log/mosquitto
RUN chown mosquitto:mosquitto -R /var/log/mosquitto

ENTRYPOINT ["/run.sh"]
CMD ["mosquitto"]
