FROM node:16-alpine
ENV NODE_ENV=production
WORKDIR /opt/app

RUN apk add git

COPY package.json package-lock.json ./
RUN npm install

COPY tsconfig.json webpack.config.js ./

COPY ./api-server ./api-server
COPY ./delta-inputs ./delta-inputs
COPY ./types ./types
RUN ./node_modules/.bin/tsc --sourceMap false
RUN ./node_modules/.bin/webpack -p --env=production

CMD ["node", "./built/api-server/index.js"]

USER node
