version: '3'

services:
  clickhouse:
    image: yandex/clickhouse-server:21-alpine
    ports:
     - 48123:8123
     - 49000:9000
  postgis:
    image: mdillon/postgis:11-alpine
    ports:
     - 45432:5432
    restart: always
    environment:
      POSTGRES_USER: signalk
      POSTGRES_PASSWORD: signalk
      POSTGRES_DB: signalk
  mqtt:
    image: signalkstash/mosquitto
    build:
      context: .
      dockerfile: Dockerfile.mosquitto
    ports:
     - 41883:1883
     - 49883:9883
    volumes:
      - mosquitto-data:/var/lib/mosquitto
    restart: always

volumes:
  mosquitto-data:
