version: '3'

services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
     - 48123:8123
     - 49000:9000
  postgis:
    image: mdillon/postgis:10-alpine
    ports:
     - 45432:5432
    restart: always
    environment:
      POSTGRES_USER: signalk
      POSTGRES_PASSWORD: signalk
      POSTGRES_DB: signalk
  mqtt:
    image: signalkstash/mosquitto
    build:
      context: .
      dockerfile: Dockerfile.mosquitto
    ports:
     - 41883:1883
    volumes:
      - mosquitto-data-test:/var/lib/mosquitto
      - mosquitto-log-test:/var/log/mosquitto
    restart: always

volumes:
  mosquitto-data-test:
  mosquitto-log-test:
