version: '3'

services:
  api-server:
    image: signalkstash/api-server:${TAG}
    ports:
      - 3000:3000
    restart: always
    env_file:
      - docker-prod.env
    environment:
      ENVIRONMENT: production
  mqtt-input:
    image: signalkstash/mqtt-input:${TAG}
    restart: always
    env_file:
      - docker-prod.env
    environment:
      ENVIRONMENT: production
      MQTT_BROKER: mqtt://mqtt
  postgis:
    image: mdillon/postgis:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: signalk
      POSTGRES_PASSWORD: signalk
      POSTGRES_DB: signalk
  clickhouse:
    image: yandex/clickhouse-server
    volumes:
      - clickhousedata:/var/lib/clickhouse
    ports:
      - 127.0.0.1:8123:8123
  mqtt:
    image: signalkstash/mosquitto:prod
    ports:
      - 1883:1883  # plaintext mqtt
      - 8883:8883  # mqtt over tls v1.2
      - 9883:9883  # mqtt over ws
    volumes:
      - mosquitto-data:/var/lib/mosquitto
      - ./mosquitto_tls.conf:/etc/mosquitto.d/mosquitto_tls.conf
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
  grafana:
    image: "grafana/grafana"
    ports:
      - 3001:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_INSTALL_PLUGINS: vertamedia-clickhouse-datasource
      GF_SERVER_ROOT_URL: ${GRAFANA_ROOT_URL}
      COMPOSE_ENV_NAME: prod

volumes:
  pgdata:
  clickhousedata:
  mosquitto-data:
  grafana-data:
