version: '3'

services:
  api-server:
    image: signalkstash/api-server:${TAG}
    ports:
      - 3000:3000
    restart: always
    env_file:
      - docker-prod.env
    environment:
      ENVIRONMENT: production
  mqtt-input:
    image: signalkstash/mqtt-input:${TAG}
    restart: always
    env_file:
      - docker-prod.env
    environment:
      ENVIRONMENT: production
      MQTT_BROKER: mqtt://mqtt
  postgis:
    image: mdillon/postgis:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: signalk
      POSTGRES_PASSWORD: signalk
      POSTGRES_DB: signalk
  clickhouse:
    image: yandex/clickhouse-server
    volumes:
      - clickhousedata:/var/lib/clickhouse
  mqtt:
    image: signalkstash/mosquitto:prod
    ports:
      - 8883:8883
    volumes:
      - mosquitto-data:/var/lib/mosquitto
      - ./mosquitto_tls.conf:/etc/mosquitto.d/mosquitto_tls.conf
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always

volumes:
  pgdata:
  clickhousedata:
  mosquitto-data:
