version: '3'

services:
  postgis:
    image: timescale/timescaledb-postgis:1.2.1-pg11
    ports:
     - 50400:5432
    volumes:
     - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: signalk
      POSTGRES_PASSWORD: signalk
      POSTGRES_DB: signalk
  postgis-test:
    image: timescale/timescaledb-postgis:1.2.1-pg11
    ports:
     - 50500:5432
    restart: always
    environment:
      POSTGRES_USER: signalk
      POSTGRES_PASSWORD: signalk
      POSTGRES_DB: signalk
  mqtt:
    image: jihartik/signalk-stash-mosquitto
    build:
      context: .
      dockerfile: Dockerfile.mosquitto
    ports:
     - 11883:1883
    volumes:
      - mosquitto-data:/var/lib/mosquitto
      - mosquitto-log:/var/log/mosquitto
    restart: always
  mqtt-test:
    image: jihartik/signalk-stash-mosquitto
    build:
      context: .
      dockerfile: Dockerfile.mosquitto
    ports:
     - 21883:1883
    volumes:
      - mosquitto-data:/var/lib/mosquitto
      - mosquitto-log:/var/log/mosquitto
      # Overwrite mosquitto-auth.conf to authenticate against postgis-test DB
      - ./mosquitto-auth.test.conf:/etc/mosquitto.d/mosquitto-auth.conf
    restart: always

volumes:
  pgdata:
  mosquitto-data:
  mosquitto-log:
