version: '3'

services:
  clickhouse-test:
    image: yandex/clickhouse-server
    ports:
     - 48123:8123
     - 49000:9000
  postgis-test:
    image: mdillon/postgis:10-alpine
    ports:
     - 40500:5432
    restart: always
    environment:
      POSTGRES_USER: signalk
      POSTGRES_PASSWORD: signalk
      POSTGRES_DB: signalk
  mqtt-test:
    image: jihartik/signalk-stash-mosquitto
    build:
      context: .
      dockerfile: Dockerfile.mosquitto
    ports:
     - 41883:1883
    volumes:
      - mosquitto-data-test:/var/lib/mosquitto
      - mosquitto-log-test:/var/log/mosquitto
      # Overwrite mosquitto-auth.conf to authenticate against postgis-test DB
      - ./mosquitto-auth.test.conf:/etc/mosquitto.d/mosquitto-auth.conf
    restart: always

volumes:
  mosquitto-data-test:
  mosquitto-log-test:
