version: '3.7'

services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
     - 28123:8123
     - 29000:9000
  postgis:
    image: mdillon/postgis:11-alpine
    ports:
     - 25432:5432
    volumes:
     - pgdata-e2e:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: signalk
      POSTGRES_PASSWORD: signalk
      POSTGRES_DB: signalk
  mqtt:
    image: signalkstash/mosquitto
    build:
      context: .
      dockerfile: Dockerfile.mosquitto
    ports:
     - 21883:1883
     - 29883:9883
    volumes:
      - mosquitto-data-e2e:/var/lib/mosquitto
    restart: always
  grafana:
    image: "grafana/grafana"
    ports:
      - 23001:3000
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources/e2e:/etc/grafana/provisioning/datasources
      - ./grafana-signalk-plugins/:/var/lib/grafana/plugins/
    environment:
      GF_INSTALL_PLUGINS: vertamedia-clickhouse-datasource
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: signalk-datasource,signalk-trackmap
  signalk:
    image: signalk/signalk-server:latest
    entrypoint:
    - /home/node/signalk/bin/signalk-server
    - --sample-nmea0183-data
    - --override-timestamps
    environment:
    - DEBUG=@signalk/mqtt-stasher,signalk:interfaces:plugins
    ports:
     - 3002:3000
    volumes:
     - ./e2e/dotsignalk:/home/node/.signalk
    restart: always
    privileged: true
    init: true

volumes:
  pgdata-e2e:
  mosquitto-data-e2e:
