version: '3'

services:
  postgis:
    image: mdillon/postgis:10-alpine
    ports:
     - 50400:5432
    volumes:
     - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: signalk
      POSTGRES_PASSWORD: signalk
      POSTGRES_DB: signalk
  postgis-test:
    image: mdillon/postgis:10-alpine
    ports:
     - 50500:5432
    restart: always
    environment:
      POSTGRES_USER: signalk
      POSTGRES_PASSWORD: signalk
      POSTGRES_DB: signalk
  mqtt:
    image: eclipse-mosquitto
    ports:
     - 11883:1883
    volumes:
      - mosquitto:/mosquitto/data
    restart: always

volumes:
  pgdata:
  mosquitto:
