FROM node:alpine
ENV NODE_ENV=production
WORKDIR /opt/app

RUN apk add git

COPY package.json package-lock.json ./
RUN npm install

COPY tsconfig.json webpack.config.js ./

COPY ./api-server ./api-server
COPY ./types ./types
RUN ./node_modules/.bin/tsc --outDir ./built/api-server --sourceMap false
RUN ./node_modules/.bin/webpack -p

CMD ["node", "./built/api-server/index.js"]

USER node
