version: '3'

services:

  postgis:
    image: mdillon/postgis:10-alpine
    ports:
     - 50400:5432
    volumes:
     - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: signalk
      POSTGRES_PASSWORD: signalk
      POSTGRES_DB: signalk

volumes:
  pgdata:
