FROM node:16-alpine as builder
WORKDIR /opt/app

RUN apk add git

COPY package.json package-lock.json ./
RUN npm install

COPY tsconfig.json ./

COPY ./api-server ./api-server
COPY ./delta-inputs ./delta-inputs
COPY ./types ./types
RUN ./node_modules/.bin/tsc --sourceMap false



FROM node:16-alpine
ENV NODE_ENV=production
WORKDIR /opt/app

COPY package.json package-lock.json ./
RUN npm install
COPY --from=builder /opt/app/built .

CMD ["node", "./delta-inputs/mqtt-runner.js"]

USER node
