FROM node:alpine
ENV NODE_ENV=production
WORKDIR /opt/app

COPY package.json package-lock.json ./
RUN npm install

COPY tsconfig.json ./

COPY ./api-server ./api-server
COPY ./delta-inputs ./delta-inputs
RUN ./node_modules/.bin/tsc

CMD ["node", "./built/delta-inputs/mqtt-runner.js"]

USER node
