version: 2.1
commands:
  build:
    description: 'Builds project dependencies'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-signal-k-stash-{{ checksum "package.json" }}
      - run:
          command: npm install
      - save_cache:
          key: v1-signal-k-stash-{{ checksum "package.json" }}
          paths:
            - ~/.cache
            - ~/.npm

jobs:
  unit-test:
    machine: true
    steps:
      - build
      - run:
          command: make test
      - store_test_results:
          path: test_reports

  integration-test:
    machine: true
    steps:
      - build
      - run:
          command: make docker-test-up
      - run:
          command: make start-test
          background: true
      - run:
          name: 'Wait for test server to start'
          command: npx wait-on "http://localhost:43000/tracks?context=self"
      - run:
          command: make test-integration
      - store_test_results:
          path: test_reports

workflows:
  version: 2
  unit-test:
    jobs:
      - unit-test
  integration-test:
    jobs:
      - integration-test
