version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-signal-k-stash-{{ checksum "package.json" }}
      - run:
          command: npm install
      - save_cache:
          key: v1-signal-k-stash-{{ checksum "package.json" }}
          paths:
            - ~/.cache
            - ~/.npm
      - run:
          command: make docker-test-up
      - run:
          command: make test
