---
- hosts: all
  remote_user: stash

  vars_files:
    - secrets.yml

  tasks:
    - name: Copy Docker compose file to remote
      copy:
        src: ../docker-compose.prod.yml
        dest: docker-compose.prod.yml

    - name: Generate Docker environment file
      copy:
        dest: docker-prod.env
        content: |
          SIGNALK_STASH_MQTT_USERNAME={{ secrets.prod.mqtt_runner.username }}
          SIGNALK_STASH_MQTT_PASSWORD={{ secrets.prod.mqtt_runner.password }}

    - name: Copy Mosquitto TLS configuration file
      copy:
        src: mosquitto_tls.conf
        dest: mosquitto_tls.conf

    - name: Setup production Docker containers
      docker_service:
        project_name: signalk-stash-prod
        project_src: .
        pull: true
        files:
          - docker-compose.prod.yml
      environment:
        # This will be given as -e command line parameter
        TAG: "{{ docker_tag }}"