---
- hosts: all
  remote_user: stash

  vars:
    hostname: "{{ lookup('env','SIGNALK_STASH_PROD_HOST') }}"
    mqtt_runner:
      username: "{{ lookup('env','SIGNALK_STASH_MQTT_USERNAME') }}"
      password: "{{ lookup('env','SIGNALK_STASH_MQTT_PASSWORD') }}"

  tasks:
    - name: Copy Docker compose file to remote
      copy:
        src: ../docker-compose.prod.yml
        dest: docker-compose.prod.yml

    - name: Fail if MQTT runner credentials are missing
      fail:
        msg: "Mqtt runner credentials are missing. Set SIGNALK_STASH_MQTT_USERNAME and SIGNALK_STASH_MQTT_PASSWORD variables."
      when: mqtt_runner.username == "" or mqtt_runner.password == ""

    - name: Generate Docker environment file
      copy:
        dest: docker-prod.env
        content: |
          SIGNALK_STASH_MQTT_USERNAME={{ mqtt_runner.username }}
          SIGNALK_STASH_MQTT_PASSWORD={{ mqtt_runner.password }}

    - name: Copy Mosquitto TLS configuration file
      template:
        src: mosquitto_tls.conf.j2
        dest: mosquitto_tls.conf

    - name: Setup production Docker containers
      docker_service:
        project_name: signalk-stash-prod
        project_src: .
        pull: true
        files:
          - docker-compose.prod.yml
      environment:
        # This will be given as -e command line parameter
        TAG: "{{ docker_tag }}"