---
- hosts: all
  remote_user: root

  tasks:
  - name: Install/update packages
    apt: pkg={{ item }} state=latest
    with_items:
      - git
      - curl
      - htop
      - tmux
      - telnet

  - name: Add Docker APT key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
      update_cache: yes

  - name: Install Docker
    apt: pkg=docker-ce state=latest
