name: Cypress tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    environment: CI

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: |
        make docker-test-up
        make start-test &
        npx wait-on "http://localhost:43000/tracks?context=self"
    - run: make test-integration
      env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}