name: Build and push Docker containers

on:
  push:
    branches:
    - master
    - dev-docker

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    environment: CI

    strategy:
      matrix:
        app: ['api-server', 'mqtt-input']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: signalkstash/${{ matrix.app }}
          tag-sha: true # add git short SHA as Docker tag
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          file: Dockerfile.${{ matrix.app }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
